### PR TITLE
404 page works if requested url is not in redirectorDB, reformat

### PR DESCRIPTION
**Pull request by thesabbir**
Untested though :)
please let me know

### CODE REVIEW

**Comment by thesabbir** [comment]
tested, works :)

**Comment by SohanChy** [comment]
I tested as well, will merge now, just cleaned up some extra html tags that got leftover.

**Comment by SohanChy** [comment]
Merged,
You cleaned up the whole thing and made it a lot more presentable.
Thanks a lot for the PR. :+1:

**Comment by thesabbir** [comment]
Thanks! Good work btw :)

**Pull request merged**
